-- 1. Verificando VAGAS
SELECT * FROM VAGAS;

-- 2. Verificando as CANDIDATAS
SELECT * FROM CANDIDATAS;

-- 3. Verificando as Candidaturas
SELECT * FROM CANDIDATURAS;

-- 4. Verificando a conexão
SELECT 
    CANDIDATURAS.ID_CANDIDATURA,
    CANDIDATAS.NOME AS CANDIDATA,
    CANDIDATAS.EMAIL,
    VAGAS.TITULO AS VAGA,
    VAGAS.EMPRESA
FROM CANDIDATURAS
INNER JOIN CANDIDATAS 
    ON CANDIDATAS.ID_CANDIDATA = CANDIDATURAS.ID_CANDIDATA
INNER JOIN VAGAS 
    ON VAGAS.ID_VAGA = CANDIDATURAS.ID_VAGA;