-- 1. Tabela VAGAS (tabela de origem 1)
CREATE TABLE VAGAS (
    ID_VAGA INTEGER PRIMARY KEY NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    EMPRESA VARCHAR(100) NOT NULL,
    SALARIO DECIMAL NOT NULL
);
 
-- 2. Tabela CANDIDATAS (tabela de origem 2)
CREATE TABLE CANDIDATAS (
    ID_CANDIDATA INTEGER PRIMARY KEY NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);
 
-- 3. Tabela CANDIDATURAS (tabela associativa - resolve o N:N)
CREATE TABLE CANDIDATURAS (
    ID_CANDIDATURA INTEGER PRIMARY KEY NOT NULL,
    DATA_ENVIO DATETIME NOT NULL,
    ID_VAGA INTEGER NOT NULL,
    ID_CANDIDATA INTEGER NOT NULL,
    FOREIGN KEY (ID_VAGA) REFERENCES VAGAS(ID_VAGA),
    FOREIGN KEY (ID_CANDIDATA) REFERENCES CANDIDATAS(ID_CANDIDATA)
);